import prisma from "../utils/db.js";
import { spawn } from "child_process";
import path from "path";
import { fileURLToPath } from "url";
import os from "os";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generateSeatingPlan = async (req, res) => {
  const { examId } = req.params;

  try {
    // Fetch exam with nested course info
    const exam = await prisma.exam.findUnique({
      where: { id: Number(examId) },
      include: {
        subject: {
          include: {
            semester: {
              include: {
                course: true,
              },
            },
          },
        },
      },
    });

    if (!exam) {
      return res.status(404).json({ success: false, message: "Exam not found" });
    }

    // Fetch students for this course and semester
    const students = await prisma.student.findMany({
      where: {
        courseId: exam.subject.semester.courseId,
        semesterId: exam.subject.semester.id,
      },
      select: {
        id: true,
        college: true,
      },
    });

    if (!students.length) {
      return res.status(400).json({ success: false, message: "No students found for this exam" });
    }

    // Fetch room assignments with benches for this exam
    const roomAssignments = await prisma.roomAssignment.findMany({
      where: { examId: Number(examId) },
      include: {
        room: {
          include: {
            benches: {
              orderBy: [{ row: "asc" }, { column: "asc" }],
            },
          },
        },
      },
    });

    if (!roomAssignments.length) {
      return res.status(400).json({ success: false, message: "No room assignments found for this exam" });
    }

    // Prepare payload for Python GA script
    const inputPayload = {
      examId: exam.id,
      students,
      roomAssignments,
    };

    const pythonPath = path.join(__dirname, "../algorithm/seating_algorithm.py");

    // Use python on Windows, python3 on others
    const pythonCmd = os.platform() === "win32" ? "python" : "python3";

    const python = spawn(pythonCmd, [pythonPath]);

    let result = "";
    let errorOutput = "";

    python.stdin.write(JSON.stringify(inputPayload));
    python.stdin.end();

    python.stdout.on("data", (data) => {
      result += data.toString();
    });

    python.stderr.on("data", (data) => {
      errorOutput += data.toString();
      console.error("Python Error:", data.toString());
    });

    python.on("close", async (code) => {
      if (code !== 0) {
        console.error("Python script exited with code", code);
        return res.status(500).json({
          success: false,
          message: "Python script error",
          error: errorOutput,
        });
      }

      try {
        const parsedSeats = JSON.parse(result.trim());

        if (!Array.isArray(parsedSeats) || !parsedSeats.length) {
          return res.status(500).json({
            success: false,
            message: "No seats generated by the algorithm",
          });
        }

        // Deactivate old seating plans for this exam
        await prisma.seatingPlan.updateMany({
          where: {
            examId: Number(examId),
            isActive: true,
          },
          data: { isActive: false },
        });

        // Create new seating plan
        const seatingPlan = await prisma.seatingPlan.create({
          data: {
            examId: Number(examId),
            isActive: true,
          },
        });

        // Prepare seat records
        const seatsData = parsedSeats.map((seat) => ({
          studentId: seat.studentId,
          benchId: seat.benchId,
          position: seat.position,
          seatingPlanId: seatingPlan.id,
        }));

        // Insert seats in bulk
        await prisma.seat.createMany({ data: seatsData });

        res.json({
          success: true,
          message: "Seating plan generated successfully",
          seatingPlanId: seatingPlan.id,
        });
      } catch (err) {
        console.error("Error parsing JSON or DB error:", err);
        res.status(500).json({ success: false, message: "Failed to generate seating plan" });
      }
    });
  } catch (err) {
    console.error("Internal server error:", err);
    res.status(500).json({ success: false, message: "Internal server error" });
  }
};

export const getAllSeatingPlan = async (req, res) => {
  try {
    const seatingPlans = await prisma.seatingPlan.findMany({
      include: {
        exam: {
          include: {
            subject: {
              include: {
                semester: {
                  include: {
                    course: true,
                  },
                },
              },
            },
          },
        },
        seats: {
          include: {
            student: {
              select: {
                id: true,
                college: true,
                symbolNumber: true,
              },
            },
            bench: {
              include: {
                room: {
                  select: {
                    id: true,
                    roomNumber: true,
                    block: true,
                    floor: true,
                  },
                },
              },
            },
          },
        },
      },
      orderBy: {
        id: "desc",
      },
    });

    res.json({
      success: true,
      message: "Seating plans retrieved successfully",
      data: seatingPlans,
    });
  } catch (error) {
    console.error("Error fetching seating plans:", error);
    res.status(500).json({
      success: false,
      message: "Failed to fetch seating plans",
      error: error.message,
    });
  }
};
